<?php

namespace Database\Seeders;

use App\Models\Article;
use App\Models\Categorie;
use App\Models\MarcheCategory;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ArticleFruitSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $categoryId = Categorie::where('code', 'FRU')->firstOrFail()->id;
        $marche_category_id = MarcheCategory::where('nom', 'légumes et fruits')->firstOrFail()->id;
        
        $articles = [
             [
                    'reference' => 'FRU65',
                    'designation' => 'Abricots',
                    'unite_mesure' => ' kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 40,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'FRU66',
                    'designation' => 'Ananas  ',
                    'unite_mesure' => 'kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 40,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'FRU67',
                    'designation' => 'Avocat',
                    'unite_mesure' => 'Kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 120,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'FRU68',
                    'designation' => 'Bananes',
                    'unite_mesure' => ' kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 1200,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'FRU69',
                    'designation' => 'Cerise',
                    'unite_mesure' => 'Kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 30,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'FRU70',
                    'designation' => 'Clémentine / Mandarines',
                    'unite_mesure' => ' kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 1000,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'FRU71',
                    'designation' => 'Fraise',
                    'unite_mesure' => ' kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 500,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'FRU72',
                    'designation' => 'Framboise',
                    'unite_mesure' => 'kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 40,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'FRU73',
                    'designation' => 'Fruit de la passion',
                    'unite_mesure' => 'kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 20,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'FRU74',
                    'designation' => 'Grenades',
                    'unite_mesure' => 'kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 80,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'FRU75',
                    'designation' => 'Kaki',
                    'unite_mesure' => 'kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 10,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'FRU76',
                    'designation' => 'Kiwi',
                    'unite_mesure' => 'kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 60,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'FRU77',
                    'designation' => 'Mangue',
                    'unite_mesure' => 'kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 30,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'FRU78',
                    'designation' => 'Melon',
                    'unite_mesure' => ' kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 140,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'FRU79',
                    'designation' => 'Mertile',
                    'unite_mesure' => 'kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 20,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'FRU80',
                    'designation' => 'Oranges à jus',
                    'unite_mesure' => 'Kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 200,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'FRU81',
                    'designation' => 'Oranges de table',
                    'unite_mesure' => ' kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 1800,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'FRU82',
                    'designation' => 'Pamplemousse',
                    'unite_mesure' => 'Kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 100,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'FRU83',
                    'designation' => 'Pastèque',
                    'unite_mesure' => ' kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 120,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'FRU84',
                    'designation' => 'Pêche',
                    'unite_mesure' => 'kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 100,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'FRU85',
                    'designation' => 'Poires',
                    'unite_mesure' => ' kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 700,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'FRU86',
                    'designation' => 'Pomme verte',
                    'unite_mesure' => 'kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 20,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'FRU87',
                    'designation' => 'Pommes fruit',
                    'unite_mesure' => ' kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 1600,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'FRU88',
                    'designation' => 'Prunes',
                    'unite_mesure' => ' kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 50,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'FRU89',
                    'designation' => 'Raisin vert/ noir',
                    'unite_mesure' => ' kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 200,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            ];

        Article::insert($articles);

    }
}
