<?php

namespace Database\Seeders;

use App\Models\Article;
use App\Models\Categorie;
use App\Models\MarcheCategory;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ArticleLegumeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $categoryId = Categorie::where('code', 'LEG')->firstOrFail()->id;
        $marche_category_id = MarcheCategory::where('nom', 'légumes et fruits')->firstOrFail()->id;

        $articles = [
            [
                    'reference' => 'LEG1',
                    'designation' => 'Ail en vrac',
                    'unite_mesure' => ' kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 60,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'LEG2',
                    'designation' => 'Artichauts',
                    'unite_mesure' => 'kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 400,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'LEG3',
                    'designation' => 'Asperge frais ',
                    'unite_mesure' => 'botte',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 10,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'LEG4',
                    'designation' => 'Aubergine',
                    'unite_mesure' => 'kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 800,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'LEG5',
                    'designation' => 'Basilic frais ',
                    'unite_mesure' => 'Btte',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 30,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'LEG6',
                    'designation' => 'Betteraves sans branches',
                    'unite_mesure' => ' kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 1000,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'LEG7',
                    'designation' => 'Brocolis ',
                    'unite_mesure' => 'kg ',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 30,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'LEG8',
                    'designation' => 'Cardon ',
                    'unite_mesure' => 'kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 60,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'LEG9',
                    'designation' => 'Carottes sans branches',
                    'unite_mesure' => ' kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 2000,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'LEG10',
                    'designation' => 'Cèleri en branches',
                    'unite_mesure' => ' kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 60,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'LEG11',
                    'designation' => 'Cèleri rave',
                    'unite_mesure' => 'kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 30,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'LEG12',
                    'designation' => 'Champignon cèpes',
                    'unite_mesure' => 'kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 30,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'LEG13',
                    'designation' => 'Champignon de paris frais',
                    'unite_mesure' => 'kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 30,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'LEG14',
                    'designation' => 'Champignon portobello',
                    'unite_mesure' => 'kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 10,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'LEG15',
                    'designation' => 'Choux de Bruxelles',
                    'unite_mesure' => 'kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 10,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'LEG16',
                    'designation' => 'Choux fleur',
                    'unite_mesure' => ' kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 800,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'LEG17',
                    'designation' => 'Choux rouges',
                    'unite_mesure' => 'kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 10,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'LEG18',
                    'designation' => 'Choux vert',
                    'unite_mesure' => ' kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 500,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'LEG19',
                    'designation' => 'Ciboulette',
                    'unite_mesure' => 'botte',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 30,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'LEG20',
                    'designation' => 'Citron frais',
                    'unite_mesure' => ' kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 300,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'LEG21',
                    'designation' => 'Citron vert',
                    'unite_mesure' => 'kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 10,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'LEG22',
                    'designation' => 'Coing',
                    'unite_mesure' => 'kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 50,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'LEG23',
                    'designation' => 'Concombre',
                    'unite_mesure' => ' kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 1000,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'LEG24',
                    'designation' => 'Coriandre',
                    'unite_mesure' => ' kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 240,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'LEG25',
                    'designation' => 'Courge rouge',
                    'unite_mesure' => ' kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 500,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'LEG26',
                    'designation' => 'Courgette vert ronde ',
                    'unite_mesure' => 'kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 30,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'LEG27',
                    'designation' => 'Courgettes vertes longues',
                    'unite_mesure' => ' kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 1000,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'LEG28',
                    'designation' => 'Endives ',
                    'unite_mesure' => 'kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 6,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'LEG29',
                    'designation' => 'Epinards frais',
                    'unite_mesure' => 'kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 40,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'LEG30',
                    'designation' => 'Fenouil frais',
                    'unite_mesure' => 'kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 100,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'LEG31',
                    'designation' => 'Feves frais ',
                    'unite_mesure' => 'kg ',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 60,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'LEG32',
                    'designation' => 'Gingembre frais',
                    'unite_mesure' => 'kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 6,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'LEG33',
                    'designation' => 'Haricot mange tout ',
                    'unite_mesure' => ' kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 6,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'LEG34',
                    'designation' => 'Haricot vert Frais',
                    'unite_mesure' => ' kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 500,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'LEG35',
                    'designation' => 'Laurier en  branche',
                    'unite_mesure' => ' botte',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 10,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'LEG36',
                    'designation' => 'Marron',
                    'unite_mesure' => 'kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 6,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'LEG37',
                    'designation' => 'Mauve frais ',
                    'unite_mesure' => 'kg ',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 6,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'LEG38',
                    'designation' => 'Menthe fraiche',
                    'unite_mesure' => 'kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 20,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'LEG39',
                    'designation' => 'Navet sans branches',
                    'unite_mesure' => ' kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 700,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'LEG40',
                    'designation' => 'Oignon échalote',
                    'unite_mesure' => 'kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 30,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'LEG41',
                    'designation' => 'Oignons sans branches',
                    'unite_mesure' => ' kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 2800,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'LEG42',
                    'designation' => 'Origan frais ',
                    'unite_mesure' => 'botte',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 10,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'LEG43',
                    'designation' => 'Persil en Kg',
                    'unite_mesure' => ' kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 300,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'LEG44',
                    'designation' => 'Petit pois',
                    'unite_mesure' => ' kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 500,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'LEG45',
                    'designation' => 'Piment fort ',
                    'unite_mesure' => 'kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 2,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'LEG46',
                    'designation' => 'Poireaux en botte ',
                    'unite_mesure' => ' kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 260,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'LEG47',
                    'designation' => 'Poivron jaune',
                    'unite_mesure' => 'kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 50,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'LEG48',
                    'designation' => 'Poivron rouge',
                    'unite_mesure' => 'kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 50,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'LEG49',
                    'designation' => 'Poivrons verts (doux)',
                    'unite_mesure' => ' kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 900,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'LEG50',
                    'designation' => 'Pomme de terre',
                    'unite_mesure' => ' kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 5200,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'LEG51',
                    'designation' => 'Pomme nouvelle ',
                    'unite_mesure' => 'kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 100,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'LEG52',
                    'designation' => 'Radis',
                    'unite_mesure' => 'kg ',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 20,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'LEG53',
                    'designation' => 'Romarin frais',
                    'unite_mesure' => 'botte',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 30,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'LEG54',
                    'designation' => 'Salade de jeune pousse',
                    'unite_mesure' => 'botte',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 30,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'LEG55',
                    'designation' => 'Salade feuille de betterave ',
                    'unite_mesure' => 'kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 10,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'LEG56',
                    'designation' => 'Salade frisée',
                    'unite_mesure' => 'kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 20,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'LEG57',
                    'designation' => 'Salade romaine ',
                    'unite_mesure' => 'botte ',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 20,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'LEG58',
                    'designation' => 'Salade mache',
                    'unite_mesure' => 'botte',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 20,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'LEG59',
                    'designation' => 'Salade roquette',
                    'unite_mesure' => 'kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 10,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'LEG60',
                    'designation' => 'Salade verte laitue',
                    'unite_mesure' => 'kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 300,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'LEG61',
                    'designation' => 'Thym en branche ',
                    'unite_mesure' => 'botte',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 40,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'LEG62',
                    'designation' => 'Tomate cerise jaune',
                    'unite_mesure' => 'kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 20,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'LEG63',
                    'designation' => 'Tomates Cerise rouge ',
                    'unite_mesure' => ' kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 40,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            [
                    'reference' => 'LEG64',
                    'designation' => 'Tomates Fraîches',
                    'unite_mesure' => ' kg',
                    'categorie_id' => $categoryId,
                    'marche_category_id' => $marche_category_id,
                    'categorie_principale_id' => 1,
                    'nature_prestation_id' => 1,
                    'taux_tva' => 0,
                    'seuil_minimal' => 0,
                    'seuil_maximal' => 4000,
                    'est_actif' => 1,
                    'in_marche' => 0,
                ],
            ];

        Article::insert($articles);

    }
}
