<?php

namespace Database\Seeders;

use App\Models\Article;
use App\Models\Categorie;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ArticleEpicerieSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $categoryId = Categorie::where('code', 'EP')->firstOrFail()->id;

        $articles = [
[
        'reference' => 'EP1',
        'designation' => 'Abricots sec ',
        'unite_mesure' => 'kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 10,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP2',
        'designation' => 'Amandes grosses décortiquées',
        'unite_mesure' => 'kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 30,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP3',
        'designation' => 'Beurre Beldi',
        'unite_mesure' => 'kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 6,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP4',
        'designation' => 'Blé dur concassé (Herbel)',
        'unite_mesure' => 'kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 20,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP5',
        'designation' => 'Cacahouettes décortiquées',
        'unite_mesure' => 'kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 10,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP6',
        'designation' => 'Cardamone',
        'unite_mesure' => 'kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 2,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP7',
        'designation' => 'Citron confit le kg',
        'unite_mesure' => ' kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 30,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP8',
        'designation' => 'Clou de girofle',
        'unite_mesure' => 'kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 3,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP9',
        'designation' => 'Coriande en grain  ',
        'unite_mesure' => 'kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 3,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP10',
        'designation' => 'Couscous en sachet  de 1 kg  de calibre moyen (Tria ou similaire)',
        'unite_mesure' => 'kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 40,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP11',
        'designation' => 'Couscous en vrac 1°choix',
        'unite_mesure' => ' kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 300,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP12',
        'designation' => 'Dattes 1er choix',
        'unite_mesure' => 'kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 80,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP13',
        'designation' => 'Farine Blé dur',
        'unite_mesure' => 'kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 30,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP14',
        'designation' => 'Farine patisserie en sac de 5 kg ',
        'unite_mesure' => 'sac',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 50,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP15',
        'designation' => 'Farine en vrac ',
        'unite_mesure' => 'kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 400,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP16',
        'designation' => 'Fèves sèches decortiquées  en vrac ',
        'unite_mesure' => ' kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 20,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP17',
        'designation' => 'Fleur de safran sachet de 1 gr ',
        'unite_mesure' => 'sachet',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 30,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP18',
        'designation' => 'Figues seches ',
        'unite_mesure' => 'kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 10,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP19',
        'designation' => 'Gomme Arabic',
        'unite_mesure' => 'sachet',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 20,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP20',
        'designation' => 'Gomme de xantan en paquet de 0,400 gr',
        'unite_mesure' => 'pt',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 2,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP21',
        'designation' => 'Grains d\'anis',
        'unite_mesure' => 'kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 2,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP22',
        'designation' => 'Grains de sésame',
        'unite_mesure' => 'kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 10,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP23',
        'designation' => 'Haricot blanc en vrac (grosse)',
        'unite_mesure' => ' kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 400,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP24',
        'designation' => 'Huile d\'olive extra vierge(bt 1 litre)',
        'unite_mesure' => 'L',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 400,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP25',
        'designation' => 'Lait concentre boite de  410 gr  non sucré',
        'unite_mesure' => 'Boite',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 20,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP26',
        'designation' => 'Lait concentré boite de 410 gr sucré',
        'unite_mesure' => 'Boite',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 20,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP27',
        'designation' => 'lait de coco  1/2 ',
        'unite_mesure' => 'bte',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 30,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP28',
        'designation' => 'Lait frais UHT',
        'unite_mesure' => 'L',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 400,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP29',
        'designation' => 'Lentilles en vrac (Nylon)',
        'unite_mesure' => 'kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 400,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP30',
        'designation' => 'Levure boulangère',
        'unite_mesure' => 'kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 10,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP31',
        'designation' => 'Miel 4/4 ',
        'unite_mesure' => 'Boite',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 10,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP32',
        'designation' => 'Noisette ',
        'unite_mesure' => 'kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 10,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP33',
        'designation' => 'Noix  de muscade la pièce',
        'unite_mesure' => 'pce',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 140,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP34',
        'designation' => 'Noix de coco  râpé ',
        'unite_mesure' => 'Kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 10,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP35',
        'designation' => 'Noix décortiqués',
        'unite_mesure' => 'kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 10,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP36',
        'designation' => 'Noix de cajou ',
        'unite_mesure' => 'kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 10,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP37',
        'designation' => 'Olives confit le Kg ',
        'unite_mesure' => 'Kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 40,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP38',
        'designation' => 'Origan 25g',
        'unite_mesure' => 'flacon ',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 10,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP39',
        'designation' => 'Pistache decortique ',
        'unite_mesure' => 'kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 6,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP40',
        'designation' => 'Pistache non decortique ',
        'unite_mesure' => 'kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 10,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP41',
        'designation' => 'Pois cassé en vrac',
        'unite_mesure' => ' kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 80,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP42',
        'designation' => 'Pois chiche en vrac  ',
        'unite_mesure' => ' kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 100,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP43',
        'designation' => 'Rass el hanout',
        'unite_mesure' => 'kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 2,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP44',
        'designation' => 'Smen beldi',
        'unite_mesure' => 'Kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 5,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP45',
        'designation' => 'Sucre glacé',
        'unite_mesure' => ' kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 30,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP46',
        'designation' => 'Sucre glucose boite de 4/4 ',
        'unite_mesure' => 'bt',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 20,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP47',
        'designation' => 'Sucre morceaux (café et thé)',
        'unite_mesure' => ' kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 80,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP48',
        'designation' => 'Sucre semoule',
        'unite_mesure' => ' kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 1400,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP49',
        'designation' => 'Thym seché 15g',
        'unite_mesure' => 'flacon ',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 30,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP50',
        'designation' => 'Cuisse de dinde fumée variée',
        'unite_mesure' => 'kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 8,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP51',
        'designation' => 'Filet de Dinde cuit fumé',
        'unite_mesure' => 'kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 8,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP52',
        'designation' => 'Jambon de bœuf fumé',
        'unite_mesure' => 'kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 8,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP53',
        'designation' => 'Magret de canard fumet',
        'unite_mesure' => 'kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 4,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP54',
        'designation' => 'Mortadelle',
        'unite_mesure' => 'kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 8,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP55',
        'designation' => 'Pastrami de bœuf fumé ',
        'unite_mesure' => 'kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 8,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP56',
        'designation' => 'Poitrine de bœuf fumée',
        'unite_mesure' => 'kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 8,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP57',
        'designation' => 'Salami de bœuf fumé',
        'unite_mesure' => 'kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 10,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP58',
        'designation' => 'Saucisson cuit à l`\'ail',
        'unite_mesure' => 'kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 10,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP59',
        'designation' => 'Saumon fumée',
        'unite_mesure' => 'Kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 8,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP60',
        'designation' => 'Surimi',
        'unite_mesure' => 'Kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 10,
        'est_actif' => 1,
        'in_marche' => 0,
    ],

[
        'reference' => 'EP61',
        'designation' => 'Lait en poudre (boite de 2,4 kg)',
        'unite_mesure' => 'Boite',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 140,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP62',
        'designation' => 'Huile de noix',
        'unite_mesure' => 'L',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 4,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP63',
        'designation' => 'Huile de riz',
        'unite_mesure' => 'L',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 4,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP64',
        'designation' => 'Huile végetale',
        'unite_mesure' => 'L',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 1000,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP65',
        'designation' => 'huile vegetale en bidon de 5 lt ',
        'unite_mesure' => 'bidon ',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 160,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP66',
        'designation' => 'Pate farfalle ',
        'unite_mesure' => 'kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 30,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP67',
        'designation' => 'Pate Filou',
        'unite_mesure' => 'kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 10,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP68',
        'designation' => 'Pate penne',
        'unite_mesure' => 'kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 200,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP69',
        'designation' => 'Pates Spaghetti     ',
        'unite_mesure' => 'kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 240,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP70',
        'designation' => 'Pates Spaghetti à l\'encre de chine ',
        'unite_mesure' => 'kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 10,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP71',
        'designation' => 'Pates tagliatelle ',
        'unite_mesure' => ' kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 40,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP72',
        'designation' => 'Pates Vermicelle',
        'unite_mesure' => 'kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 60,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP73',
        'designation' => 'Pates Vermicelle de riz',
        'unite_mesure' => 'kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 4,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP74',
        'designation' => 'Risotto arborio',
        'unite_mesure' => 'kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 10,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP75',
        'designation' => 'Risotto scotti',
        'unite_mesure' => 'kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 10,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP76',
        'designation' => 'Riz Basmati premier choix',
        'unite_mesure' => 'kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 20,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP77',
        'designation' => 'Riz long glacé  ',
        'unite_mesure' => ' kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 60,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP78',
        'designation' => 'Riz en vrac de bonne qualité ',
        'unite_mesure' => 'kg ',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 600,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP79',
        'designation' => 'Sel de cuisine en sachet  de 0,2Kg',
        'unite_mesure' => 'st',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 300,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP80',
        'designation' => 'Semoule 1° choix en vrac',
        'unite_mesure' => ' kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 100,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP81',
        'designation' => 'Amlou amande',
        'unite_mesure' => 'kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 4,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP82',
        'designation' => 'Beurre en vrac   ',
        'unite_mesure' => 'Kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 360,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP83',
        'designation' => 'Thé noir en pt 25 sachets',
        'unite_mesure' => ' pqt',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 10,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP85',
        'designation' => 'Agar agar ',
        'unite_mesure' => 'kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 2,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP86',
        'designation' => 'Amandes effilées',
        'unite_mesure' => 'kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 14,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP87',
        'designation' => 'Amandes en poudre',
        'unite_mesure' => ' kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 14,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP88',
        'designation' => 'Ananas en tranche en bte de 4/4',
        'unite_mesure' => 'bte',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 40,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP89',
        'designation' => 'Anchoix en filet 0,250 g',
        'unite_mesure' => 'bte',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 40,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP90',
        'designation' => 'Anchoix marinée 0,250 g',
        'unite_mesure' => 'bte',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 6,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP91',
        'designation' => 'Arôme artificiel 0,28 ml',
        'unite_mesure' => 'fla',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 20,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP92',
        'designation' => 'Avoine en pqt de 0,500 g ',
        'unite_mesure' => 'Pqt ',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 30,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP93',
        'designation' => 'Basilic 18 gr',
        'unite_mesure' => 'flq',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 20,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP94',
        'designation' => 'Beurre d\'arachide 0,500 g',
        'unite_mesure' => 'boite',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 14,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP95',
        'designation' => 'Beurre en portion Individuel 10 gr en paquet de 100 unites ',
        'unite_mesure' => 'paquet',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 6,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP96',
        'designation' => 'Café moulu arabica 1er choix',
        'unite_mesure' => ' kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 200,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP97',
        'designation' => 'Café soluble  en pot de 90 gr',
        'unite_mesure' => 'pot',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 20,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP98',
        'designation' => 'Cannelle en batonette (cigare)',
        'unite_mesure' => 'kg ',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 4,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP99',
        'designation' => 'Cannelle en branche ',
        'unite_mesure' => 'kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 4,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP100',
        'designation' => 'Cannelle moulue ',
        'unite_mesure' => 'kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 6,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP101',
        'designation' => 'Capre boite de 4/4',
        'unite_mesure' => 'bt',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 50,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP102',
        'designation' => 'Capres en flacon de 125g',
        'unite_mesure' => 'fl',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 30,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP103',
        'designation' => 'Capsule de café 1er choix de 10u',
        'unite_mesure' => 'pqt',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 10,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP104',
        'designation' => 'Cerise confites  DGF',
        'unite_mesure' => 'kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 6,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP105',
        'designation' => 'Champignon en bte 0,400g',
        'unite_mesure' => 'bte',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 60,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP106',
        'designation' => 'Champignon en bte de 4/4',
        'unite_mesure' => 'bte',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 60,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP107',
        'designation' => 'Champignon en bte de 3/1 ',
        'unite_mesure' => 'bte ',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 10,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP108',
        'designation' => 'Chocolat 73%',
        'unite_mesure' => 'kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 60,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP109',
        'designation' => 'Chocolat à tartiner de 0,5 kg ',
        'unite_mesure' => 'pot ',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 20,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP110',
        'designation' => 'Chocolat noir /blanc couverture en pistole 60 % et plus ',
        'unite_mesure' => 'Kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 20,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP111',
        'designation' => 'Chocolat au lait couverture en pistole 45 % et plus ',
        'unite_mesure' => 'kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 14,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP112',
        'designation' => 'Chocolat poudre 1er choix bte 500g',
        'unite_mesure' => 'boite',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 14,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP113',
        'designation' => 'Cœur de palmier de 0,4 kg',
        'unite_mesure' => 'bte',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 30,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP114',
        'designation' => 'Colorant artificiel   25g',
        'unite_mesure' => 'flq',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 30,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP115',
        'designation' => 'Concentré de tomate bte 4/4                    ',
        'unite_mesure' => ' bte',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 540,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP116',
        'designation' => 'Concentré de tomate bte 370 gr                   ',
        'unite_mesure' => 'bte',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 20,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP117',
        'designation' => 'Confiture en portion Individuel 20 gr en paquet de 224 unites ',
        'unite_mesure' => 'paquet',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 6,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP118',
        'designation' => 'Confiture abricot bt 4/4',
        'unite_mesure' => 'bte',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 240,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP119',
        'designation' => 'Confiture fraise bt 4/4',
        'unite_mesure' => 'bte',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 80,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP120',
        'designation' => 'Cornichon boite de 370 gr',
        'unite_mesure' => 'flq',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 30,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP121',
        'designation' => 'Cornichon en boite de 200gr',
        'unite_mesure' => 'bt',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 40,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP122',
        'designation' => 'Crème pâtisserie en pt de 800g',
        'unite_mesure' => 'pqt',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 4,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP123',
        'designation' => 'Crème chantilly 1er choix 0,500ml',
        'unite_mesure' => 'flq',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 20,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP124',
        'designation' => 'Crème fraîche U H T sucré ',
        'unite_mesure' => 'L',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 80,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP125',
        'designation' => 'Crème fraîche UHT non sucré 1ier choix',
        'unite_mesure' => 'L',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 360,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP126',
        'designation' => 'Cube de Bouillons pqt de 10 cube',
        'unite_mesure' => 'pqt',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 20,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP127',
        'designation' => 'Cumin moulu ',
        'unite_mesure' => 'kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 20,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP128',
        'designation' => 'Curcuma moulu ',
        'unite_mesure' => 'kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 6,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP129',
        'designation' => 'Curry en flacon de 35 gr',
        'unite_mesure' => 'fla',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 10,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP130',
        'designation' => 'Demi-glace de 605 gr',
        'unite_mesure' => 'boite',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 30,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP131',
        'designation' => 'Eau de Fleur d\'Oranger de 0,5 l',
        'unite_mesure' => 'blle',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 40,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP132',
        'designation' => 'Eau gazeuse 1L',
        'unite_mesure' => 'Blle',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 150,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP133',
        'designation' => 'Eau gazeuse de Luxe 1L',
        'unite_mesure' => 'L',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 40,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP134',
        'designation' => 'Eau minirale de 33 cl           ',
        'unite_mesure' => 'Blle',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 600,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP135',
        'designation' => 'Eau minirale de 50 cl',
        'unite_mesure' => 'blle',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 600,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP136',
        'designation' => 'Eau minirale de 1,50 L           ',
        'unite_mesure' => 'Blle',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 600,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP137',
        'designation' => 'Eau minirale de 0,75 L bouteille en verre         ',
        'unite_mesure' => 'Blle',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 50,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP138',
        'designation' => 'blé tendre en paquet  de 1 kg  Eblé  ou similaire ',
        'unite_mesure' => 'paquet',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 10,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP139',
        'designation' => 'Estragon flacon de 5 g',
        'unite_mesure' => 'flq',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 20,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP140',
        'designation' => 'Etoile d\'annis',
        'unite_mesure' => 'kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 4,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP141',
        'designation' => 'Flan en pot de 80 gr ',
        'unite_mesure' => 'pot',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 200,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP142',
        'designation' => 'Feuille de Nori pqt 10 feuille',
        'unite_mesure' => 'pqt',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 4,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP143',
        'designation' => 'Fondant (sucre) Vrac',
        'unite_mesure' => 'Kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 10,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP144',
        'designation' => 'Gélatine Feuille pqt 50 feuille',
        'unite_mesure' => 'pqt',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 10,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP145',
        'designation' => 'Gélatine en poudre ',
        'unite_mesure' => 'kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 2,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP146',
        'designation' => 'Gingembre moulu',
        'unite_mesure' => 'kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 20,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP147',
        'designation' => 'Gousse de vanille',
        'unite_mesure' => 'gousse',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 20,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP148',
        'designation' => 'Gros sel',
        'unite_mesure' => 'kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 10,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP149',
        'designation' => 'Herbes de provence en flacon de 18 gr',
        'unite_mesure' => 'flq',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 20,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP150',
        'designation' => 'Huile de sesam 0,200 ml 100 %',
        'unite_mesure' => 'fla',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 20,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP151',
        'designation' => 'Jus d\'Ananas  bte 1litre',
        'unite_mesure' => 'L',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 60,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP152',
        'designation' => 'Jus de fraise bte 1litre',
        'unite_mesure' => 'L',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 40,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP153',
        'designation' => 'Jus de pêche bte 1litre',
        'unite_mesure' => 'L',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 40,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP154',
        'designation' => 'jus de pomme',
        'unite_mesure' => 'L',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 40,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP155',
        'designation' => 'Jus de raisin bte 1litre',
        'unite_mesure' => 'L',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 40,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP156',
        'designation' => 'Jus de tomate bte  de 1 lt',
        'unite_mesure' => 'L',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 40,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP157',
        'designation' => 'Jus d\'orange bte 1litre',
        'unite_mesure' => 'L',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 70,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP158',
        'designation' => 'Jus mix des fruits bte 1litre',
        'unite_mesure' => 'L',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 40,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP159',
        'designation' => 'Levure chimique pqt de 10 sachets',
        'unite_mesure' => 'Pquet',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 30,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP160',
        'designation' => 'Limonade bouteille de 1 lt',
        'unite_mesure' => 'litre',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 400,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP161',
        'designation' => 'limonade canette de 50 Cl',
        'unite_mesure' => 'U',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 400,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP162',
        'designation' => 'Limonade cannette de 25 Cl',
        'unite_mesure' => 'U',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 800,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP163',
        'designation' => 'Mais 4/4',
        'unite_mesure' => 'bte',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 60,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP164',
        'designation' => 'Mais boite de1/4',
        'unite_mesure' => 'bte',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 50,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP165',
        'designation' => 'Maizena 0,180g',
        'unite_mesure' => 'pqt',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 70,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP166',
        'designation' => 'Maquereau à l\'huile  2/1(2kg)',
        'unite_mesure' => 'bte',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 50,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP167',
        'designation' => 'Maquereau à l\'huile de 125 gr',
        'unite_mesure' => 'bte',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 40,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP168',
        'designation' => 'Margarine pétrissage pqt 500g  ',
        'unite_mesure' => ' kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 100,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP169',
        'designation' => 'Miel en portion Individuel 20g en paquet de 224 portions',
        'unite_mesure' => 'paquet',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 2,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP170',
        'designation' => 'Moules en boite de 115 gr',
        'unite_mesure' => 'bte',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 12,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP171',
        'designation' => 'Moutarde en pot de 200gr',
        'unite_mesure' => 'pot',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 40,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP172',
        'designation' => 'Moutarde pot de 1,2 kg',
        'unite_mesure' => 'pot',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 40,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP173',
        'designation' => 'Nappage  4/4',
        'unite_mesure' => 'bte',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 20,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP174',
        'designation' => 'Olives noires /vertes 4/4avec noyau',
        'unite_mesure' => ' bte',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 30,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP175',
        'designation' => 'Olives noires/vertes 5/1 avec noyau ',
        'unite_mesure' => 'bte',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 30,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP176',
        'designation' => 'Olives vertes 5/1 sans noyau ',
        'unite_mesure' => 'bte',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 40,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP177',
        'designation' => 'Olives vertes 4/4  Sans noyau ',
        'unite_mesure' => 'bte',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 40,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP178',
        'designation' => 'Paprika douce en vrac le Kg',
        'unite_mesure' => 'Kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 20,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP179',
        'designation' => 'Pêches au sirop bte 4/4',
        'unite_mesure' => 'bte',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 60,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP180',
        'designation' => 'Pectine jaune 500 gr NH',
        'unite_mesure' => 'bte',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 2,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP181',
        'designation' => 'Pectine jaune 500- NH',
        'unite_mesure' => 'bte',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 2,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP182',
        'designation' => 'Piment fort en vrac le Kg',
        'unite_mesure' => 'Kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 2,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP183',
        'designation' => 'Poires au sirop en bte 4/4',
        'unite_mesure' => 'bte',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 60,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP184',
        'designation' => 'Poivre blanc moulu le Kg',
        'unite_mesure' => 'Kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 5,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP185',
        'designation' => 'Poivre noir en grain le Kg',
        'unite_mesure' => 'Kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 3,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP186',
        'designation' => 'Poivre noir moulu le Kg',
        'unite_mesure' => 'Kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 20,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP187',
        'designation' => 'Poudre de cacao',
        'unite_mesure' => 'kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 16,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP188',
        'designation' => 'Praliné amande ',
        'unite_mesure' => 'Kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 6,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP189',
        'designation' => 'Praliné noisette ',
        'unite_mesure' => 'Kg ',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 6,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP190',
        'designation' => 'Pruneaux          ',
        'unite_mesure' => 'Kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 80,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP191',
        'designation' => 'Raisins secs ',
        'unite_mesure' => ' kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 50,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP192',
        'designation' => 'Romarin en flacon de 25 gr',
        'unite_mesure' => 'flq',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 30,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP193',
        'designation' => 'Saccharine en flacon de 72 gr',
        'unite_mesure' => 'flq',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 4,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP194',
        'designation' => 'Safran en paquet de 100 sachets',
        'unite_mesure' => 'pqt',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 30,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP195',
        'designation' => 'Salade fruit en boite 4/4',
        'unite_mesure' => 'Bte',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 10,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP196',
        'designation' => 'Sauce anglaise 295 ml',
        'unite_mesure' => 'fla',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 20,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP197',
        'designation' => 'Sauce Ketchup flacon 0,310 gr',
        'unite_mesure' => 'fla',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 30,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP198',
        'designation' => 'Sauce Ketchup flacon 500 gr',
        'unite_mesure' => 'fla',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 30,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP199',
        'designation' => 'Sauce oyster flacon 0,150 gr',
        'unite_mesure' => 'fla',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 20,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP200',
        'designation' => 'Sauce piquante en flacon de 50g',
        'unite_mesure' => 'fl',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 50,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP201',
        'designation' => 'Sauce Soja flacon de 0,150g',
        'unite_mesure' => 'fla',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 40,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP202',
        'designation' => 'Sel de table en flacon de 0,400gr',
        'unite_mesure' => 'fla',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 40,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP203',
        'designation' => 'Sirop d\'amande bouteille de 75 cl ',
        'unite_mesure' => 'bte',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 4,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP204',
        'designation' => 'Sirop de canne bouteille de 75 cl',
        'unite_mesure' => 'bte',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 4,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP205',
        'designation' => 'Sirop de glucose bouteille de 75 cl ',
        'unite_mesure' => 'bte',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 2,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP206',
        'designation' => 'Sirop de fraise bouteille de 75 cl ',
        'unite_mesure' => 'bte',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 4,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP207',
        'designation' => 'Sirop de framboise bouteille de 75 cl',
        'unite_mesure' => 'bte',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 4,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP208',
        'designation' => 'Sirop de grenadine bouteille de 75 cl',
        'unite_mesure' => 'bte',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 4,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP209',
        'designation' => 'Sirop de menthe bouteille de 75 cl ',
        'unite_mesure' => 'bte',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 4,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP210',
        'designation' => 'Sirop de mojito bouteille de 70 cl ',
        'unite_mesure' => 'bte',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 6,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP211',
        'designation' => 'Sucre Brun (Cassonade)',
        'unite_mesure' => 'Kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 4,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP212',
        'designation' => 'Sucre vanille pqt de 10s',
        'unite_mesure' => ' pqt',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 80,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP213',
        'designation' => 'Tabasco flacon de 60 ml',
        'unite_mesure' => 'flq',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 20,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP214',
        'designation' => 'Thon en bte de 4/4 (1 Kg)  ',
        'unite_mesure' => 'Bte',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 40,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP215',
        'designation' => 'Thon en bte de 2/1 ( 1,7 kg)',
        'unite_mesure' => 'bte',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 80,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP216',
        'designation' => 'Tisane variée 1ier choix en paquet de 20 sachets',
        'unite_mesure' => 'pt',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 20,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP217',
        'designation' => 'Toping caramel, chocolat, fraise 1L',
        'unite_mesure' => 'flq',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 20,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP218',
        'designation' => 'Vanille en flacon 28 ml',
        'unite_mesure' => 'fla',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 20,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP219',
        'designation' => 'Vermicelle chinoise en pqt de 0,5 kg',
        'unite_mesure' => ' kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 10,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP220',
        'designation' => 'Vinaigre balsamique en flacon en verre de 50 cl  ',
        'unite_mesure' => 'flq',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 6,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP221',
        'designation' => 'Vinaigre Blanc 50cl',
        'unite_mesure' => 'flq',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 70,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP222',
        'designation' => 'Vinaigre de pomme en flacon en verre de 50 cl',
        'unite_mesure' => 'flq',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 6,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP223',
        'designation' => 'Vinaigre de riz en flacon en verre de 150 ml ',
        'unite_mesure' => 'flq',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 6,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP224',
        'designation' => 'Vinaigre xeres flacon en verre de 50 cl ',
        'unite_mesure' => 'flq',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 6,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP225',
        'designation' => 'Vinaigre flacon de 50 cl',
        'unite_mesure' => ' fl',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 80,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP226',
        'designation' => 'Warka \'Feuille de Briques\'',
        'unite_mesure' => 'Kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 40,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP227',
        'designation' => 'Wasabi 43 gr ',
        'unite_mesure' => 'tube',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 4,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP228',
        'designation' => 'Yaourt 110 grs  ',
        'unite_mesure' => 'Unité ',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 4000,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP229',
        'designation' => 'Fromage blanc en boite de 190 gr',
        'unite_mesure' => 'kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 10,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP230',
        'designation' => 'Fromage bleu',
        'unite_mesure' => 'kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 6,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP231',
        'designation' => 'Fromage brie',
        'unite_mesure' => 'kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 6,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP232',
        'designation' => 'Fromage camembert',
        'unite_mesure' => 'kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 6,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP233',
        'designation' => 'Fromage de chèvre en croute',
        'unite_mesure' => 'kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 6,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP234',
        'designation' => 'Fromage gouda au cumin',
        'unite_mesure' => 'kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 6,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP235',
        'designation' => 'Fromage gouda nature',
        'unite_mesure' => 'kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 6,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP236',
        'designation' => 'Fromage gruyère',
        'unite_mesure' => 'Kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 20,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP237',
        'designation' => 'Fromage mozzarella',
        'unite_mesure' => 'kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 14,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP238',
        'designation' => 'Fromage parmesan',
        'unite_mesure' => 'kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 14,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP239',
        'designation' => 'Fromage Raclette paquet  de 420 gr ',
        'unite_mesure' => 'pt',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 6,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP240',
        'designation' => 'Fromage ration en paquet de 8 portion ',
        'unite_mesure' => 'pqt',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 800,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP241',
        'designation' => 'Fromage ricotta',
        'unite_mesure' => 'kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 10,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP242',
        'designation' => 'Fromage roquefort',
        'unite_mesure' => 'kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 4,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP243',
        'designation' => 'Fromage rouge le Kg',
        'unite_mesure' => 'Kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 60,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
[
        'reference' => 'EP244',
        'designation' => 'Mascarpone',
        'unite_mesure' => 'kg',
        'categorie_id' => $categoryId,
        'categorie_principale_id' => 1,
        'nature_prestation_id' => 1,
        'taux_tva' => 0,
        'seuil_minimal' => 0,
        'seuil_maximal' => 10,
        'est_actif' => 1,
        'in_marche' => 0,
    ],
];

    Article::insert($articles);

    }
}
